### PR TITLE
fix: set metafile flag in a way that prevents Serverless v3.x from overwriting it

### LINKED ISSUE #8: Only works when metafile: true passed in config
This plugin requires that serverless-esbuild plugin is configured with `metafile: true` option. Otherwise it gives an error complaining the metadata cannot be found. 

I see that the code is meant to [set the option automatically](https://github.com/adriencaccia/serverless-analyze-bundle-plugin/blob/dd94d06a21c36fbd1248e223683fa60d8b6a49e4/plugin/serverlessAnalyzeBundle.ts#L41), however on the latest Serverless v3.x this doesn't work anymore. It appears that the custom.esbuild settings are overwritten, so the metafile flag is "lost" just before the build happens.

### PR DESCRIPTION
**Pull request by coyoteecd**
I moved the setting of metafile flag to the constructor, as this seems to work correctly on the most recent Serverless v3 versions.

Closes #8

### CODE REVIEW

**Comment by coyoteecd** [comment]
@adriencaccia could you have a look at this PR and merge + publish it to npm, please?

**Comment by adriencaccia** [comment]
Hey @coyoteecd, sorry for the delay.

Thanks for the contribution!

I couldn't reproduce the bug on my end, I tested with `serverless@3.21.0`.
But if there are versions in the 3.x range that does not work with the current code, I am willing to make the change, since it does not break anything and works :slightly_frowning_face:

File: plugin/serverlessAnalyzeBundle.ts [hunk 1]
```diff
@@ -48,5 +40,16 @@ export class ServerlessAnalyzeBundlePlugin implements Plugin {
         await this.bundleVisualizer();
       },
     };
+
+    // The plugin requires metafile option to be true
+    // We set it here (and not within a hook) because Serverless Framework keeps copies of service configuration
+    // therefore overwriting changes made by hook functions
+    //
```
Comment (adriencaccia) [inline plugin/serverlessAnalyzeBundle.ts]: We can remove this useless comment line

**Review by adriencaccia — CHANGES_REQUESTED** [review]
I really like the comment :heart_eyes: 

I just have one small change request before merging

File: plugin/serverlessAnalyzeBundle.ts (hunk 1 above)
Comment (coyoteecd) [reply plugin/serverlessAnalyzeBundle.ts]: For what is worth, the empty line was intentional (sort of a separator to clearly mark it as a block comment).
Anyway, your repo, I removed it and forcepushed

**Comment by adriencaccia** [comment]
Thanks @coyoteecd 🚀
